language: rust
os:
    - linux
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    - sudo apt-get install yasm
    - wget http://www.ffmpeg.org/releases/ffmpeg-2.2.4.tar.bz2
    - tar -xjf ffmpeg-2.2.4.tar.bz2
    - cd ffmpeg-2.2.4
    - ./configure --enable-shared --disable-static --prefix=/usr/local
    - make -j2
    - sudo make install
script:
    - cargo build
